Fix error with docker API + bump MINIMUM_DOCKER_API_VERSION to 1.21
* Fix docker API error:

"Error: 'module' object has no attribute 'Client'"
See: http://docker-py.readthedocs.io/en/stable/change-log.html
-> docker.Client has been renamed to docker.APIClient

* Fix Warning regarding the MINIMUM_DOCKER_API_VERSION"

"~/.local/lib/python2.7/site-packages/docker/api/client.py:161:
UserWarning: The minimum API version supported is 1.21, but you are
using version 1.15. It is recommended you either upgrade Docker Engine
or use an older version of Docker SDK for Python.
'Python.'.format(MINIMUM_DOCKER_API_VERSION, self._version)"